name: Build and Test intEx8

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: sudo apt update && sudo apt install -y gcc make

      - name: Compile test_intEx8
        run: echo "Will be accoumplished soon!\n"

      - name: Run Tests
        run: echo "Will be accoumplished soon!\n"
